website/views.py
from flask import Blueprint, flash, render_template, request, redirect, url_for, abort
from werkzeug.utils import secure_filename
from .models import Event, Comment, Booking
from .forms import EventCreationForm, CommentForm, BookingForm
from . import db
import uuid, os
from flask_login import login_required, current_user
from datetime import datetime

bp = Blueprint('main', __name__)

@bp.route('/')
def index():
    events = db.session.scalars(db.select(Event)).all()
    categories = db.session.scalars(db.select(Event.category).distinct())
    return render_template('index.html', events=events, categories=categories)

@bp.route('/<category>')
def category(category):
    exists = Event.query.filter_by(category=category).first()
    if exists is None:
        abort(404)
    events = db.session.scalars(db.select(Event).where(Event.category==category))
    categories = db.session.scalars(db.select(Event.category).distinct())
    return render_template('index.html', events=events, categories=categories)

@bp.route('/event/<id>')
def event(id):
    exists = Event.query.filter_by(id=id).first()
    if exists is None:
        abort(404)
    event = db.session.scalar(db.select(Event).where(Event.id==id))
    if datetime.now() > event.dateTime:
        event.status="Inactive"
        db.session.commit() 
        flash('This event is now inactive.')
    comment_form = CommentForm()
    booking_form = BookingForm()
    return render_template('event.html', event=event, comment_form=comment_form, booking_form=booking_form)

@bp.route('/event/<event>/comment', methods=['GET', 'POST'])  
@login_required
def comment(event):  
    form = CommentForm()  
    event = db.session.scalar(db.select(Event).where(Event.id==event))

    if form.validate_on_submit():  
        comment = Comment(
            content=form.content.data, 
            event=event, 
            user=current_user,
            timestamp=datetime.now()
        ) 
        db.session.add(comment) 
        db.session.commit() 
        print('User comment has been added', 'success')
        flash('Your comment has been added.')

    return redirect(url_for('main.event', id=event.id))

@bp.route('/event/<event>/booking', methods=['GET', 'POST'])  
@login_required
def booking(event):  
    form = BookingForm()  
    event = db.session.scalar(db.select(Event).where(Event.id==event))

    if form.validate_on_submit():
        tickets=form.tickets.data
        
        if tickets > event.ticketsAvailable or tickets <= 0 or event.ticketsAvailable == 0:
            print('Booking failed')
            flash('Your order cannot be placed.')
        else:
            event.ticketsAvailable-=tickets
            booking = Booking(
                ticketNum=tickets, 
                event=event, 
                user=current_user
                )
            db.session.add(booking) 
            db.session.commit() 
            print('Booking added', 'success')
            flash('Thank you! Your booking is complete.')

            if event.ticketsAvailable == 0: 
                event.status="Sold out"
                db.session.commit() 
                print('Event sold out!')

    return redirect(url_for('main.event', id=event.id))

@bp.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    create_form = EventCreationForm()
    print('User has requested the event creation page...')

    if request.method == 'POST':

        if create_form.validate_on_submit():
            print('User has submitted the event creation form for validation...')
            # Build a filename for the image path
            filename = str(uuid.uuid4())
            # Get the uploaded file
            uploaded_file = create_form.image.data
            # Get the file extension
            _, file_extension = os.path.splitext(uploaded_file.filename)
            # Build a secure filename and append the extension
            secure_filename(uploaded_file.filename)
            filename_with_extension = filename + file_extension
            # Set the image path to the static folder
            save_path = os.path.join('website/static/img/user_events', filename_with_extension)
            # Save the uploaded file to the filesystem with the file path built above
            uploaded_file.save(save_path)
        
            event = Event(
                title=create_form.title.data,
                description=create_form.description.data,
                image='/static/img/user_events/' + filename_with_extension,
                dateTime=create_form.dateTime.data,
                price=create_form.price.data,
                ticketsAvailable=create_form.ticketsAvailable.data,
                locationName=create_form.locationName.data,
                status="Open",
                category=create_form.category.data,
                user=current_user
            )
            
            db.session.add(event)
            db.session.commit()
            flash('Thank you! Your event has been created.')

            return redirect(url_for('main.index'))
     
    return render_template('create.html', create_form=create_form)

@bp.route('/cancel/<int:id>', methods=['GET', 'POST'])
@login_required
def cancel(id):
    event = Event.query.get(id)

    event.status = "Cancelled"
    db.session.commit()
    flash('Your event has been cancelled.')
    
    return redirect(url_for('auth.user'))

website/templates/base.html
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>IAB207 Assignment 3</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/css/style.css">
    <!-- Add FontAwesome icons -->
    <script src="https://kit.fontawesome.com/42381de42c.js" crossorigin="anonymous"></script>
	<meta name="csrf-token" content="{{ csrf_token() }}">
</head>

<body>
    <!-- Header -->
    <header>

        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg sticky-top bg-light shadow-sm">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold" href="/">
                    <!-- Implement Font Awesome icons like this if you're curious homies -->
                    <i class="fa-solid fa-utensils"></i>
                    Foodie Directions
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#navbarOffcanvas" aria-controls="navbarOffcanvas">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end" tabindex="-1" id="navbarOffcanvas" aria-labelledby="navbarOffcanvasLabel">
                    <div class="offcanvas-header">
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <!-- Login button -->
                            {% if current_user.is_authenticated %}
                                <li class="nav-item ms-md-1 mt-1 mt-md-0">
                                    <a type="button" class="btn btn-outline-primary" href="/user">Profile</a>
                                </li>
                                <li class="nav-item ms-md-1 mt-1 mt-md-0">
                                    <a type="button" class="btn btn-outline-danger" href="/logout">Logout</a>
                                </li>
                            {% else %}
                                <li class="nav-item ms-md-1 mt-1 mt-md-0">
                                    <a type="button" class="btn btn-outline-primary" href="/login">Login</a>
                                </li>
                            {% endif %}
                            <!-- Create event link -->
                            <li class="nav-item ms-md-1 mt-1 mt-md-0">
                                <a type="button" class="nav-item btn btn-outline-success" href="/create">Create Event</a>
                            </li>
                        </ul>
                    </div>         
                </div>
            </div>
        </nav>
        
        {% with messages = get_flashed_messages() %}
            {% if messages %}
            <div class="container-fluid">
                <div class="row mt-3 mb-3">
                    <div class="col-md-12">
                    {% for message in messages %}
                        <div class="alert alert-info">{{ message }}</div>
                    {% endfor %}
                </div>
            </div>
            </div>
            {% endif %}
        {% endwith %}
 
        <!-- Header extensions -->
        {% block header %}
        {% endblock %}

    </header>

    <!-- Main content -->
    {% block content %}
    {% endblock %}

    <!-- Footer -->
    <div class="container mx-lg-5">
        <footer class="footer d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
                <span class="mb-3 mb-md-0 text-muted">&copy; 2023 Foodie Directions, Inc - IAB207</span>
            </div>
        </footer>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>

</html>

website/templates/bookings.html
<div class="p-4 bg-light shadow mb-4">
    <h1>Booking History</h1>
</div>
<body>
<div class="container-fluid">

    <!-- Placeholder booking card -->

    <div class="row justify-content-center">
        <div class="col-md-8 col-sm-10 col-12 mb-4">
            <div class="card event-card shadow bg-body-tertiary">
                <div class="row g-0">
                    <div class="col-8">
                        
                        <div class="col-4">
                            <img src="{{ event.image }}" class="img-fluid w-100 rounded-start event-card-img" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{ event.title }}</h5>
                                <p class="card-text">{{ booking.ticketNum }}</p>
                                <p class="card-text"><small class="text-body-secondary">{{ Booking.dateTime }}</small></p>
                                <a type="button" class="btn btn-outline-secondary btn-sm" href="/event">Event details</a>
                            </div>
                        </div>
                        <div class="col-4">
                            <img src="{{ event.image }}" class="img-fluid w-100 rounded-start event-card-img" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{ event.title }}</h5>
                                <p class="card-text">{{ booking.ticketNum }}</p>
                                <p class="card-text"><small class="text-body-secondary">{{ Booking.dateTime }}</small></p>
                                <a type="button" class="btn btn-outline-secondary btn-sm" href="/event">Event details</a>
                            </div>
                        </div>
                        <div class="col-4">
                            <img src="{{ event.image }}" class="img-fluid w-100 rounded-start event-card-img" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{ event.title }}</h5>
                                <p class="card-text">{{ booking.ticketNum }}</p>
                                <p class="card-text"><small class="text-body-secondary">{{ Booking.dateTime }}</small></p>
                                <a type="button" class="btn btn-outline-secondary btn-sm" href="/event">Event details</a>
                            </div>
                        </div>
                        <div class="col-4">
                            <img src="{{ event.image }}" class="img-fluid w-100 rounded-start event-card-img" alt="Event Image" class="img-fluid w-100 rounded-start event-card-img" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{ event.title }}</h5>
                                <p class="card-text">{{ booking.ticketNum }}</p>
                                <p class="card-text"><small class="text-body-secondary">{{ Booking.dateTime }}</small></p>
                                <a type="button" class="btn btn-outline-secondary btn-sm" href="/event">Event details</a>
                            </div>
                        </div>
                        <div class="col-4">
                            <img src="{{ event.image }}" class="img-fluid w-100 rounded-start event-card-img" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">{{ event.title }}</h5>
                                <p class="card-text">{{ booking.ticketNum }}</p>
                                <p class="card-text"><small class="text-body-secondary">{{Booking.dateTime}}</small></p>
                                <a type="button" class="btn btn-outline-secondary btn-sm" href="/event">Event details</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
{% endblock %}

website/templates/create.html
{% extends 'base.html' %}

{% block content %}
<div class="p-4 bg-light shadow mb-4">
    <h1>Create a future event...</h1>
</div>

<div class="container-fluid">

    <!-- Event creation form -->
    
    <div class="mt-5">
        <div class="container-sm">
            <form method="POST" action="{{ url_for('main.create') }}" enctype="multipart/form-data">
                {{ create_form.csrf_token }}
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        {{ create_form.title.label }} {{ create_form.title }}
                    </li>
                    <li class="list-group-item">
                        {{ create_form.description.label }} {{ create_form.description }}
                    </li>
                    <li class="list-group-item">
                        {{ create_form.image.label(class_="form-label") }} {{ create_form.image(class_="form-control", type="file") }}
                    </li>
                    <li class="list-group-item">
                        {{ create_form.dateTime.label(class_="form-label") }} {{ create_form.dateTime(class_="form-control", type="datetime-local") }}
                    </li>
                    <li class="list-group-item">
                        {{ create_form.price.label }} {{ create_form.price }}
                    </li>
                    <li class="list-group-item">
                        {{ create_form.ticketsAvailable.label }} {{ create_form.ticketsAvailable }}
                    </li>
                    <li class="list-group-item">
                        {{ create_form.locationName.label }} {{ create_form.locationName }}
                    </li>
                    <li class="list-group-item">
                        {{ create_form.category.label }} {{ create_form.category }}
                    </li>
                    <li class="list-group-item">
                        {{ create_form.submit }}
                    </li>
                </ul>
            </form>
        </div>
    </div>
</div>
{% endblock %}

website/templates/event.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">

    <div class="row mb-4">

        <!-- Event image -->
        <div class="col-12 px-0 shadow">
            <img src="{{ event.image }}" class="d-block w-100 event-img" alt="..."> 
        </div>

    </div>

    <div class="row justify-content-center mb-4">
        <!-- Event info -->
        <div class="container-fluid">
            <div class="p-3 shadow bg-body-tertiary rounded-4">
                <h1>{{ event.title }}</h1>

                <div class="row p-3">
                    <h4>${{ event.price }} ea.</h4>
                    <p class="text-muted">{{ event.status }}</p>
    
                    {% if event.status == "Open" %}
                        <!-- Buy form  -->
                        <form method="POST" action="{{ url_for('main.booking', event=event.id) }}" enctype="multipart/form-data">
                            {{ booking_form.csrf_token }}
                            <div class="form-floating mb-1">
                                {{ booking_form.tickets(class="form-control", placeholder="Tickets") }}
                                {{ booking_form.tickets.label }}
                            </div>
                            <div class="d-grid justify-content-end">
                                {{ booking_form.submit(class="btn btn-outline-success btn-sm") }}
                            </div>
                        </form>
                    {% endif %}
                </div>

                <hr />

                <div class="row p-3">
                    <p>{{ event.description }}</p>
                    <strong>{{ event.dateTime }}</strong>
                    <p>{{ event.locationName }}</p>
                    <!-- Cancel button -->
                    {% if event.user_id == current_user.id and event.status != "Cancelled" %}
                    <form action="{{ url_for('main.cancel', id=event.id) }}" method="POST" class="edit-button">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                        <input type="submit" value="Cancel Event" class="btn btn-outline-danger">
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="container-fluid">
            <div class="p-3 shadow bg-body-tertiary rounded-4">
                <!-- Comment form -->
                <!-- if fails replace with wtf.render_form(form,"/event/{0}/comment".format(event.id)) -->
                <form method="POST" action="{{ url_for('main.comment', event=event.id) }}" enctype="multipart/form-data">
                    {{ comment_form.csrf_token }}
                    <div class="form-floating mb-1">
                        {{ comment_form.content(class="form-control", placeholder="Comment", style="height: 100px") }}
                        {{ comment_form.content.label }}
                    </div>
                    <div class="d-grid justify-content-end">
                        {{ comment_form.submit(class="btn btn-outline-success btn-sm") }}
                    </div>
                </form>

                <!-- Comments -->
                {% for comment in event.comments %}
                <div class="p-2">  
                    <strong>{{comment.user.username}}</strong>
                    <span class="text-muted">&nbsp{{ comment.timestamp.strftime('%Y-%m-%d %H:%M') }}</span>
                    <p>{{ comment.content }}</p>
                </div> 
                {% endfor %}
                
            </div>
        </div>
    </div>

</div>
{% endblock %}

website/templates/eventCard.html
<style>
    .edit-button {
    position: relative;
    z-index: 2;
}
</style>

<div class="col-lg-3 col-md-4 col-sm-6 mb-3">
    <div class="card event-card shadow bg-body-tertiary">
        {% if not booking %}
            <img src="{{ event.image }}" class="card-img-top event-card-img" alt="...">
            <h5 class="card-title mt-2 ms-3">{{ event.title }}</h5>
        {% else %}
            <h5 class="card-title mt-2 ms-3">{{ booking.event.title }}</h5>
        {% endif %}
        <div class="card-body">
            {% if not booking %}
                <p class="card-text">{{ event.dateTime }}<br>{{ event.locationName }}<br>${{ event.price }} per ticket</p>
                {% if event.user_id == current_user.id and event.status != "Cancelled" %}
                    <form action="{{ url_for('main.cancel', id=event.id) }}" method="POST" class="edit-button">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                        <input type="submit" value="Cancel Event?" class="btn btn-outline-danger">
                    </form>
                {% endif %}
                <a type="button" class="btn btn-outline-success btn-sm" href="{{ url_for('main.event', id=event.id) }}">{{ event.status }}</a>
            {% else %}
                <p class="card-text">Your have {{ booking.ticketNum }} ticket(s)<br>Order ID: {{ booking.id }}</p>
                <p class="card-text text-muted">{{ booking.event.dateTime.strftime("%d/%m/%Y @ %I:%M %p") }}<br>{{ booking.event.locationName }}</p>
            {% endif %}
        </div>
    </div>
</div>

website/templates/index.html
{% extends 'base.html' %}

{% block header %}
    <!-- Jumbotron -->
    <div class="p-5 bg-light" style="background-image: url(../static/img/banner_img.jpg); background-position: center;">
        <div class="container-fluid py-5 text-center">
            <h1 class="display-5 fw-bold text-light">Discover your next gourmet adventure.</h1>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="container-fluid">

    <!-- Placeholder category buttons -->
    
    <div class="row p-3 shadow bg-body-tertiary" id="categories">
        <div class="col-12">
            <div data-bs-spy="scroll" data-bs-smooth-scroll="true" class="horizontal-scroll" tabindex="0">
                <a type="button" class="btn btn-outline-dark" href="/#categories">All</a>
                {% for category in categories %}
                    <a type="button" class="btn btn-outline-dark" href="{{ url_for('main.category', category=category) }}#categories">{{ category }}</a>
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- Event cards -->
    
    <div class="row mx-3 my-4">
        {% for event in events %}
        <div class="col-lg-3 col-md-4 col-sm-6 mb-3">
            <div class="card event-card shadow bg-body-tertiary">
                <img src="{{ event.image }}" class="card-img-top event-card-img" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ event.title }}</h5>
                    <p class="card-text">{{ event.dateTime }}<br>{{ event.locationName }}<br>${{ event.price }} per person</p>
                    <a type="button" class="btn btn-outline-success btn-sm stretched-link" href="{{ url_for('main.event', id=event.id) }}">{{ event.status }}</a>
                </div>
            </div>
        </div>    
        {% endfor %}
    </div>
</div>
{% endblock %}

website/templates/login.html
{% extends 'base.html' %}

{% block content %}

<div class="mt-2 mt-md-5">

  <div class="container">

    <h3 class="">Login</h3>

    <form method="POST" action="{{ url_for('auth.login') }}" enctype="multipart/form-data">
      {{ login_form.csrf_token }}
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          {{ login_form.email.label }} {{ login_form.email }}
        </li>
        <li class="list-group-item">
          {{ login_form.password.label }} {{ login_form.password }}
        </li>
        <li class="list-group-item">
          <div class="form-check">
            {{ login_form.remember_me }} 
            {{ login_form.remember_me.label }}
            {{ login_form.submitLogin }}
          </div>
        </li>
      </ul>
    </form>

  </div>

  <h2 class="my-5 mx-auto text-center">Or if you're new...</h2>

  <div class="container-sm">

    <h3>Registration</h3>

    <form method="POST" action="{{ url_for('auth.login') }}" enctype="multipart/form-data">
      {{ registration_form.csrf_token }}
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          {{ registration_form.username.label }} {{ registration_form.username }}
        </li>
        <li class="list-group-item">
          {{ registration_form.email.label }} {{ registration_form.email }}
        </li>
        <li class="list-group-item">
          {{ registration_form.password.label }} {{ registration_form.password }}
          {{ registration_form.confirm_password.label }} {{ registration_form.confirm_password }}
          <div id="passwordHelpBlock" class="form-text">
            Your password must be 8-20 characters long, contain letters and numbers, and must not contain spaces, special characters, or emoji.
          </div>
        </li>
        <li class="list-group-item">
          {{ registration_form.submitRegistration }}
        </li>
      </ul>
    </form>

  </div>

</div>

{% endblock %}

website/templates/purchase_ticket.html
{% extends 'base.html' %}

{% block content %}

<head>
  <meta charset="UTF-8">
  <title>Event Ticket Purchase</title>
</head>
<body>
  <h1>Event Ticket Purchase</h1>

  <form action="your-processing-script" method="POST">

    <h2>Billing Details</h2>

    <label for="fullName">Full Name:</label><br>
    <input type="text" id="fullName" name="fullName" required><br>

    <label for="address">Address:</label><br>
    <input type="text" id="address" name="address" required><br>

    <label for="city">City:</label><br>
    <input type="text" id="city" name="city" required><br>

    <label for="state">State:</label><br>
    <input type="text" id="state" name="state" required><br>

    <label for="zip">Zip Code:</label><br>
    <input type="text" id="zip" name="zip" required><br>

    <label for="email">Email:</label><br>
    <input type="email" id="email" name="email" required><br>

    <h2>Payment Options</h2>

    <label for="cardName">Name on Card:</label><br>
    <input type="text" id="cardName" name="cardName" required><br>

    <label for="cardNumber">Card Number:</label><br>
    <input type="text" id="cardNumber" name="cardNumber" required><br>

    <label for="expiryDate">Expiry Date (MM/YY):</label><br>
    <input type="text" id="expiryDate" name="expiryDate" required><br>

    <label for="cvv">CVV:</label><br>
    <input type="text" id="cvv" name="cvv" required><br>

    <input type="submit" value="Confirm Purchase">

  </form>
</body>

{% endblock %}

website/templates/user.html

{% extends "base.html" %}

{% block content %}
<!-- Display user's username -->
<div class="page-header mt-2 mt-md-5">
    <h3>Welcome {{ user.username }}</h3>
    <hr />
</div>
<div class="container-fluid">
    <!-- Events created by the user -->
    <h4>Events you're running...</h4>
    <div class="row mx-3 my-4">
        {% if user.events %}
            {% for event in user.events %}
                {% with %}
                    {% set event = event %}
                    {% include "eventCard.html" %}
                {% endwith %}
            {% endfor %}
        {% else %}
            <h5 class="text-muted">You have created no events...</p>
        {% endif %}
    </div>   
    
    <hr />
    <!-- Events booked by the user -->
    <h4>Your bookings...</h4>
    <div class="row mx-3 my-4">
        {% if user.bookings %}
            {% for event in user.bookings %}
                {% with %}
                    {% set event = event %}
                    {% set booking = event %}
                    {% include "eventCard.html" %}
                {% endwith %}
            {% endfor %}
        {% else %}
        
            <h5 class="text-muted">You have no bookings...</h5>
        {% endif %}
    </div>
    
</div>
{% endblock %}